server:
  port: 80
spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/food_order_system?serverTimezone=UTC
    username: root
    password: tyx1212
#  kafka:
#    bootstrap-servers: hadoop100:9092,hadoop102:9092
#    producer:
#      retries: 0
#      acks: 1
#      batch-size: 16384
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: "*"
#        linger:
#          ms: 0
#      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      #初始化消费者配置
#    consumer:
#      group-id: defaultConsumerGroup
#      enable-auto-commit: true
#      auto-commit-interval:
#      auto-offset-reset: latest
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: "*"
#          deserializer:
#            key:
#              delegate:
#                class: org.apache.kafka.common.serialization.StringDeserializer
#            value:
#              delegate:
#                class: org.springframework.kafka.support.serializer.JsonDeserializer
#        session:
#          timeout:
#            ms: 120000
#        request:
#          timeout:
#            ms: 180000
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#    listener:
#      missing-topics-fatal: false
#mybatis:
#  mapper-locations: classpath:mappers/*xml
#  type-aliases-package: com.example.foodordersystem.pojo
logging:
  level:
    root: error
